services:
  - type: web
    name: rocknroll
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
